### ISSUE TITLE
在tmux中运行termtunnel -a上传文件，经常出问题

### ISSUE THREAD

**Issue by engcn** [beordle/termtunnel#34]
![图片](https://user-images.githubusercontent.com/26758766/167847698-e817382a-ab0a-44eb-95ce-e915ad061680.png)
termtunnel -a>rz之后经常无法退出, 不必现。

环境：
termtunnel-1.6.2-linux-amd64.tar.gz
Ubuntu20.04.4

termtunnel>在这个状态时，使用tmux快捷键，Ctrl+B,z最小化窗口无反应

**Comment by beordle** [comment]
收到，目前已知道是什问题。我将增加一个退出的握手保证可靠。

**Comment by engcn** [comment]
再问两个问题：
1. 在个地方改tmux源码能解除下载限速？
2. 如果解除tmux下载速率限制， 会有什么不良影响？

**Comment by beordle** [comment]
@engcn 我已增加oneshot模式可供你尝试。
<img width="804" alt="image" src="https://user-images.githubusercontent.com/2276098/168456902-0bea142e-4f65-458d-81c0-5e04a8a27ed4.png">
1
并且默认REPL模式下，如果传输没有完成将有提示。

关于tmux修改源码的问题，你可以参考 https://v2ex.com/t/850426#r_11638667 

不良影响至少存在一个：如果经由互联网，将使互联网流量增加。

**Comment by engcn** [comment]
非常感谢，termtunnel-1.7测试可以.
