### ISSUE TITLE
服务端能支持配置文件进入termtunnel shell吗

### ISSUE THREAD

**Issue by lixiang2017** [beordle/termtunnel#44]
有很多端口需要转发，可以支持配置文件吗？比如
```bash
termtunnel -a  --config   config_file
```
config_file里每一条是local_listen/remote_listen 的命令

**Comment by beordle** [comment]
尝试下 socks5 的动态转发？或者说，我也可以增加一个 shell 中的命令来读取某个配置文件，类似 source a.sh 的体验

**Comment by lixiang2017** [comment]
动态转发可以。发现readme里只写了Share local internet with remote， 没写 share remote internet with local。
```bash
# 把本地端口3355的所有流量，都转发到远程服务器。是一个socks代理
local_listen 127.0.0.1 3355  127.0.0.1 0
```
`local_listen` 很好用，感谢！
